name: CI
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: 17
          java-package: 'jdk'
          cache: gradle

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.2.1

      - name: Run Tests
        run: ./gradlew test -Pci -Pc
      - name: JaCoCo Code Coverage Report
        uses: PavanMudigonda/jacoco-reporter@v4.5
        with:
          coverage_results_path: ${{ github.workspace }}/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.39
        if: always()
        with:
          files: "**/test-results/**/*.xml"
          check_name: Test Results
