name: CI
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: 17
          java-package: 'jdk'
          cache: gradle

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.2.1

      - name: Run Tests
        run: ./gradlew test -Pci -Pc

      - name: JaCoCo Report
        uses: Madrapps/jacoco-report@v1.2
        with:
          paths: ${{github.workspace}}/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: JaCoCo Test Coverage
          min-coverage-overall: 50
          min-coverage-changed-files: 50

      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.7.0
        with:
          jacoco-csv-file: >
            ${{github.workspace}}/bill/build/reports/jacoco/test/jacocoTestReport.csv
            ${{github.workspace}}/core/build/reports/jacoco/test/jacocoTestReport.csv
            ${{github.workspace}}/common/build/reports/jacoco/test/jacocoTestReport.csv
            ${{github.workspace}}/gateway/build/reports/jacoco/test/jacocoTestReport.csv
            ${{github.workspace}}/product/build/reports/jacoco/test/jacocoTestReport.csv
            ${{github.workspace}}/security/build/reports/jacoco/test/jacocoTestReport.csv

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.39
        if: always()
        with:
          files: "**/test-results/**/*.xml"
          check_name: Test Results
