name: Update Gradle Wrapper
on:
  push:
    branches:
      - main
      - development
  schedule:
    - cron: "0 8 1 * *"

jobs:
  update-gradle-wraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1